import { StageTemplate } from '../db/models/index.js';


// ─────────────────────────────────────────────────────────────────────────────
// PREGNANCY STAGES — ANC Schedule (WHO / NHS standard)
// Scheduled date = EDD − (40 − trigger_value) weeks
// ─────────────────────────────────────────────────────────────────────────────
const pregnancyStages = [
  {
    type: 'pregnancy',
    stage_code: 'ANC_12W',
    stage_name: 'Booking Appointment (< 12 weeks)',
    trigger_basis: 'lmp_week',
    trigger_value: 12,
    order_index: 1,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Confirm pregnancy and calculate EDD from LMP or ultrasound.',
      '• Record complete medical, surgical, and family history.',
      '• Measure weight and height; calculate BMI.',
      '• Measure blood pressure (baseline reading).',
      '• Blood tests: Full blood count (FBC), blood group & Rh factor, HIV, syphilis (VDRL), Hepatitis B surface antigen (HBsAg), rubella immunity.',
      '• Urine test: Protein, glucose, nitrites (UTI screen).',
      '• Offer nuchal translucency (NT) scan and combined first trimester screening (CFTS) for Down syndrome.',
      '• Prescribe folic acid (5mg/day), iron, calcium supplements.',
      '• Counsel on diet, lifestyle, smoking/alcohol cessation, safe medications.',
      '• Register patient in antenatal system and schedule all future visits.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_16W',
    stage_name: '16-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 16,
    order_index: 2,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Measure blood pressure and compare to baseline.',
      '• Check urine for protein and glucose.',
      '• Review and discuss results from first trimester blood tests.',
      '• Discuss results of Down syndrome / chromosomal screening.',
      '• Check for symptoms: swelling, headaches, visual disturbances.',
      '• Measure weight; monitor weight gain pattern.',
      '• Offer quadruple test (if not done at 12W) for neural tube defects.',
      '• Counsel on symptoms of pre-eclampsia to watch for.',
      '• Review and refill iron, folic acid, calcium supplements.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_25W',
    stage_name: '25-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 25,
    order_index: 3,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Measure fundal height (symphysis-fundal height — SFH) to track fetal growth.',
      '• Measure blood pressure.',
      '• Check urine for protein (pre-eclampsia screen).',
      '• Check fetal heart rate (FHR) with Doppler.',
      '• Assess fetal movements — counsel mother on kick counting.',
      '• Measure weight and check for edema (swelling in ankles/feet).',
      '• Review supplement compliance (iron, calcium).',
      '• Discuss fetal growth and expected milestones.',
      '• Arrange anomaly scan if not yet done (normally done at 18–20W).',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_28W',
    stage_name: '28-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 28,
    order_index: 4,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Glucose Tolerance Test (GTT) — screen for gestational diabetes (GDM).',
      '• Blood test: Repeat hemoglobin (Hb) — screen for anemia.',
      '• Confirm Rh (rhesus) status; administer Anti-D immunoglobulin injection to Rh-negative mothers.',
      '• Measure blood pressure.',
      '• Urine test: Protein, glucose.',
      '• Measure fundal height (SFH).',
      '• Check fetal heart rate.',
      '• Assess fetal lie and presentation.',
      '• Counsel on preterm labor warning signs.',
      '• Discuss Tdap (tetanus/diphtheria/pertussis) vaccination for mother.',
      '• Administer TT (tetanus toxoid) booster if not already given.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_31W',
    stage_name: '31-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 31,
    order_index: 5,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Review results of 28-week GTT and Hb test.',
      '• Begin closer BP monitoring (every 2–4 weeks now).',
      '• Measure fundal height (SFH).',
      '• Check fetal heart rate and fetal movements.',
      '• Assess fetal lie (head-down, breech, transverse).',
      '• Urine protein check.',
      '• Assess for signs of pre-eclampsia: headache, blurred vision, epigastric pain.',
      '• Review GDM management if diagnosed (diet, insulin if needed).',
      '• Arrange repeat growth scan if SFH is abnormal.',
      '• Counsel on birth preferences and maternity leave planning.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_34W',
    stage_name: '34-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 34,
    order_index: 6,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Assess baby\'s position — confirm if head-down (cephalic) or breech.',
      '• Discuss External Cephalic Version (ECV) if breech presentation.',
      '• Measure blood pressure and urine protein.',
      '• Measure fundal height (SFH).',
      '• Check fetal heart rate.',
      '• Discuss birth plan: preferred delivery method, pain relief options, hospital admission plan.',
      '• Review hemoglobin; initiate or continue iron therapy if anemic.',
      '• Counsel on signs of labor: regular contractions, water breaking, bloody show.',
      '• Discuss breastfeeding preparation.',
      '• Issue maternity certificate/notes if required.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_36W',
    stage_name: '36-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 36,
    order_index: 7,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Weekly monitoring begins from this point.',
      '• Group B Streptococcus (GBS) swab test (vaginal/rectal).',
      '• Confirm fetal presentation and engagement of fetal head.',
      '• Measure blood pressure.',
      '• Urine test: Protein.',
      '• Assess fetal heart rate and movement pattern.',
      '• Discuss hospital bag checklist and hospital admission plan.',
      '• Review birth plan finalization.',
      '• Counsel on when to go to hospital (contraction frequency, water breaking).',
      '• Assess for IUGR (intrauterine growth restriction) — arrange scan if SFH lag.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_38W',
    stage_name: '38-Week Checkup',
    trigger_basis: 'lmp_week',
    trigger_value: 38,
    order_index: 8,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Non-Stress Test (NST) — monitor fetal heart rate response to movements.',
      '• Biophysical Profile (BPP) if indicated.',
      '• Measure blood pressure.',
      '• Urine protein check.',
      '• Confirm fetal head engagement.',
      '• Assess amniotic fluid levels (AFI) if clinically indicated.',
      '• Discuss induction of labor: indications, process, risks/benefits.',
      '• Finalize delivery plan — c-section or vaginal.',
      '• GBS swab result review and plan antibiotic prophylaxis if positive.',
      '• Counsel on postpartum care and newborn care basics.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'ANC_40W',
    stage_name: '40-Week Checkup (Due Date)',
    trigger_basis: 'lmp_week',
    trigger_value: 40,
    order_index: 9,
    description: [
      'TASKS FOR THIS VISIT:',
      '• Assess clinical need for induction of labor (post-term risk increases after 40W).',
      '• Non-Stress Test (NST) and fetal movement assessment.',
      '• Cervical examination: assess dilation, effacement, station (Bishop score).',
      '• Amniotic Fluid Index (AFI) assessment.',
      '• Offer membrane sweep to encourage natural onset of labor.',
      '• Plan induction if not in labor by 41 weeks.',
      '• Measure blood pressure and urine protein.',
      '• Counsel on signs of labor and when to immediately go to hospital.',
      '• Emotional support and reassurance for overdue anxiety.',
    ].join('\n'),
  },
  {
    type: 'pregnancy',
    stage_code: 'DELIVERY',
    stage_name: 'Delivery',
    trigger_basis: 'lmp_week',
    trigger_value: 40,
    order_index: 10,
    description: [
      'TASKS AT DELIVERY:',
      '• Record delivery date, time, and mode (normal vaginal / assisted / c-section).',
      '• Record birth weight, APGAR score at 1 min and 5 min.',
      '• Record baby\'s name, gender, and date of birth.',
      '• Administer Vitamin K injection to newborn.',
      '• Initiate breastfeeding within 1 hour (golden hour).',
      '• Collect mother\'s postpartum vitals: BP, pulse, bleeding assessment.',
      '• Update patient record: patient status → completed, fill child_dob, delivery_date, child_name, child_gender.',
      '• Automatically generate immunization schedule for the child.',
      '• Send congratulatory WhatsApp notification with first immunization date.',
    ].join('\n'),
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// IMMUNIZATION STAGES — IAP / NIS Schedule (India)
// Scheduled date = child_dob + trigger_value days
// ─────────────────────────────────────────────────────────────────────────────
const immunizationStages = [
  {
    type: 'immunization',
    stage_code: 'IMM_BIRTH',
    stage_name: 'At Birth — BCG, OPV-0, Hep B-1',
    trigger_basis: 'child_age_days',
    trigger_value: 0,
    order_index: 1,
    description: [
      'VACCINES TO ADMINISTER:',
      '• BCG (Bacillus Calmette–Guérin) — intradermal injection, left upper arm. Protects against tuberculosis (TB).',
      '• OPV-0 (Oral Polio Vaccine, zero dose) — 2 drops orally. First polio protection.',
      '• Hep B-1 (Hepatitis B, birth dose) — IM injection, anterolateral thigh. Given within 24 hours of birth.',
      '',
      'CLINICAL TASKS:',
      '• Record birth weight, length, and head circumference.',
      '• Assess APGAR score (if not already done at delivery).',
      '• Check for jaundice, birth defects, cleft palate.',
      '• Document umbilical cord condition.',
      '• Counsel mother on breastfeeding; exclusive breastfeeding for 6 months.',
      '• Issue immunization card to parents.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_6W',
    stage_name: '6 Weeks — DTwP-1, IPV-1, Hib-1, Rota-1, PCV-1, Hep B-2',
    trigger_basis: 'child_age_days',
    trigger_value: 42,
    order_index: 2,
    description: [
      'VACCINES TO ADMINISTER:',
      '• DTwP/DTaP-1 (Diphtheria, Tetanus, Pertussis, dose 1) — IM, anterolateral thigh.',
      '• IPV-1 (Inactivated Polio Vaccine, dose 1) — IM injection or fractional intradermal.',
      '• Hib-1 (Haemophilus influenzae type b, dose 1) — IM injection.',
      '• Rotavirus-1 (Rota-1) — oral drops. Protects against rotavirus diarrhea.',
      '• PCV-1 (Pneumococcal Conjugate Vaccine, dose 1) — IM injection.',
      '• Hep B-2 (Hepatitis B, dose 2) — IM injection (often administered in pentavalent / hexavalent combo).',
      '• OPV-1 (Oral Polio Vaccine, dose 1) — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Weigh baby; assess weight gain since birth (expected ~150–200g/week).',
      '• Check head circumference and length.',
      '• Assess feeding: breastfeeding frequency, latch, supplementation.',
      '• Developmental check: social smile by 6 weeks expected.',
      '• Counsel parents: mild fever and fussiness after DTwP is normal; give paracetamol if needed.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_10W',
    stage_name: '10 Weeks — DTwP-2, IPV-2, Hib-2, Rota-2, PCV-2',
    trigger_basis: 'child_age_days',
    trigger_value: 70,
    order_index: 3,
    description: [
      'VACCINES TO ADMINISTER:',
      '• DTwP/DTaP-2 (second dose) — IM, anterolateral thigh.',
      '• IPV-2 (second dose) — IM injection.',
      '• Hib-2 (second dose) — IM injection.',
      '• Rotavirus-2 (Rota-2) — oral drops.',
      '• PCV-2 (second dose) — IM injection.',
      '• OPV-2 (second dose) — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Weigh baby and plot on growth chart (WHO Child Growth Standards).',
      '• Check for any adverse reactions to 6-week vaccines.',
      '• Developmental assessment: vocalizing (cooing), tracking objects with eyes.',
      '• Assess for any signs of developmental delay.',
      '• Counsel on introducing complementary feeding at 6 months (preparation education).',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_14W',
    stage_name: '14 Weeks — DTwP-3, IPV-3, Hib-3, Rota-3, PCV-3',
    trigger_basis: 'child_age_days',
    trigger_value: 98,
    order_index: 4,
    description: [
      'VACCINES TO ADMINISTER:',
      '• DTwP/DTaP-3 (third dose — completes primary series) — IM, anterolateral thigh.',
      '• IPV-3 (third dose) — IM injection.',
      '• Hib-3 (third dose) — IM injection.',
      '• Rotavirus-3 (Rota-3) — oral drops (completes rotavirus primary series).',
      '• PCV-3 (third dose — completes PCV primary series) — IM injection.',
      '• OPV-3 (third dose) — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Weigh baby and plot on growth chart.',
      '• Confirm completion of primary vaccine series (DTwP, OPV, IPV, Hib, Rota, PCV).',
      '• Developmental check: head control (no head lag when pulled to sit).',
      '• Counsel parents: next visit at 6 months — also introduces new vaccines.',
      '• Update and review immunization card for completeness.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_6M',
    stage_name: '6 Months — Hep B-3, Influenza-1',
    trigger_basis: 'child_age_days',
    trigger_value: 180,
    order_index: 5,
    description: [
      'VACCINES TO ADMINISTER:',
      '• Hep B-3 (Hepatitis B, third dose — completes Hep B primary series) — IM injection.',
      '• Influenza-1 (first annual flu vaccine) — IM injection. Two doses given 1 month apart for first-time recipients.',
      '• OPV-4 (Oral Polio Vaccine, dose 4) — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Weigh, measure length and head circumference; plot on growth chart.',
      '• Developmental check: sitting with support, babbling, reaching for objects.',
      '• Assess complementary feeding: has introduction of solids begun? Counsel on variety, texture, frequency.',
      '• Check for iron-deficiency anemia risk (rapid growth phase).',
      '• Counsel on dental hygiene — first tooth may be erupting.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_9M',
    stage_name: '9 Months — MMR-1, Typhoid Conjugate',
    trigger_basis: 'child_age_days',
    trigger_value: 270,
    order_index: 6,
    description: [
      'VACCINES TO ADMINISTER:',
      '• MMR-1 (Measles, Mumps, Rubella — first dose) — subcutaneous injection, upper arm. Protects against 3 major childhood viral diseases.',
      '• Typhoid Conjugate Vaccine (TCV) — IM injection (IAP recommended at 9M–12M).',
      '• OPV Booster — 2 drops orally.',
      '• Influenza-2 (second flu dose if 6M was first-ever flu vaccine) — IM injection.',
      '',
      'CLINICAL TASKS:',
      '• Weigh and measure; plot on growth chart.',
      '• Developmental check: crawling, pulling to stand, pincer grasp emerging, says "mama/dada".',
      '• Screen for iron deficiency (hemoglobin check if risk factors present).',
      '• Dental check: counsel on avoiding bottle feeding at night.',
      '• Safety counseling: baby-proofing the home (falls, choking hazards).',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_12M',
    stage_name: '12 Months — Hepatitis A-1',
    trigger_basis: 'child_age_days',
    trigger_value: 365,
    order_index: 7,
    description: [
      'VACCINES TO ADMINISTER:',
      '• Hep A-1 (Hepatitis A, first dose) — IM injection. Second dose due at 18M.',
      '',
      'CLINICAL TASKS:',
      '• Full developmental assessment at 1 year milestone:',
      '  - Walks with support or independently.',
      '  - Uses 1–3 words with meaning.',
      '  - Points to objects of interest.',
      '  - Waves bye-bye.',
      '• Weigh, measure height (now measured standing), head circumference.',
      '• Assess diet: transition from formula/breast milk to whole cow\'s milk.',
      '• Check iron levels if diet is poor.',
      '• Dental check: 6–8 teeth expected; begin fluoride toothpaste.',
      '• Autism screening (M-CHAT) if applicable.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_15M',
    stage_name: '15 Months — MMR-2, Varicella-1, PCV Booster',
    trigger_basis: 'child_age_days',
    trigger_value: 456,
    order_index: 8,
    description: [
      'VACCINES TO ADMINISTER:',
      '• MMR-2 (Measles, Mumps, Rubella — second dose) — subcutaneous injection.',
      '• Varicella-1 (Chickenpox, first dose) — subcutaneous injection.',
      '• PCV Booster (Pneumococcal Conjugate Vaccine booster dose) — IM injection.',
      '',
      'CLINICAL TASKS:',
      '• Developmental check:',
      '  - Walking steadily and independently.',
      '  - 10+ words in vocabulary.',
      '  - Follows simple 2-step instructions.',
      '  - Engages in simple pretend play.',
      '• Weigh and measure height.',
      '• Anemia screening if diet history suggests iron deficiency.',
      '• Lead exposure risk assessment (if applicable).',
      '• Review diet: variety, iron-rich foods, limiting juice/sweets.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_18M',
    stage_name: '16–18 Months — DTwP Booster-1, IPV Booster, Hib Booster, Hep A-2, Varicella-2',
    trigger_basis: 'child_age_days',
    trigger_value: 548,
    order_index: 9,
    description: [
      'VACCINES TO ADMINISTER:',
      '• DTwP/DTaP Booster-1 (first booster of primary series) — IM injection. Maintains immunity against Diphtheria, Tetanus, Pertussis.',
      '• IPV Booster (Inactivated Polio Vaccine booster) — IM injection.',
      '• Hib Booster (Haemophilus influenzae type b booster) — IM injection.',
      '• Hep A-2 (Hepatitis A, second dose — completes Hep A series) — IM injection.',
      '• Varicella-2 (Chickenpox, second dose — completes Varicella series) — subcutaneous injection.',
      '• OPV Booster — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Developmental check at 18 months:',
      '  - Runs, climbs stairs with help.',
      '  - 20+ words; starting to combine 2 words.',
      '  - Knows body parts.',
      '  - Follows 2-step instructions.',
      '• Autism screening (M-CHAT-R if not done at 12M).',
      '• Weigh and measure height.',
      '• Assess diet; counsel on avoiding processed foods, managing screen time.',
      '• Dental hygiene: all 20 primary teeth by 30M — check progress.',
      '• Safety counseling: traffic safety, water safety.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_5Y',
    stage_name: '4–6 Years — DTwP Booster-2, MMR-3, Typhoid Booster',
    trigger_basis: 'child_age_days',
    trigger_value: 1825,
    order_index: 10,
    description: [
      'VACCINES TO ADMINISTER:',
      '• DTwP/DTaP Booster-2 (second booster / pre-school booster) — IM injection. Given before school entry.',
      '• MMR-3 (third dose) — subcutaneous injection.',
      '• Typhoid Booster — IM injection.',
      '• OPV Booster — 2 drops orally.',
      '',
      'CLINICAL TASKS:',
      '• Pre-school developmental assessment:',
      '  - Speaks in full sentences.',
      '  - Can draw simple shapes, recognizes colors.',
      '  - Hops on one foot, catches ball.',
      '  - Knows full name, age, gender.',
      '• Vision and hearing test — essential before school entry.',
      '• BMI and growth assessment.',
      '• Dental assessment: primary teeth shedding; first permanent molar emerging.',
      '• Counsel on school readiness, social behavior, screen time limits.',
      '• Update immunization card with pre-school completion.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_10Y',
    stage_name: '9–12 Years — HPV (Human Papillomavirus)',
    trigger_basis: 'child_age_days',
    trigger_value: 3650,
    order_index: 11,
    description: [
      'VACCINES TO ADMINISTER:',
      '• HPV Vaccine (Human Papillomavirus) — 2-dose series (Dose 1 given now, Dose 2 given 6 months later).',
      '  - Protects against cervical cancer, anogenital cancers, and genital warts.',
      '  - Recommended by IAP for all children (girls & boys) aged 9–14 years.',
      '  - NOTE: Optional/skippable stage per clinical evaluation and parental preference.',
      '',
      'CLINICAL TASKS:',
      '• Adolescent health and lifestyle check.',
      '• Height, weight, BMI, and blood pressure monitoring.',
      '• Pubertal assessment (Tanner staging).',
      '• Education on reproductive health and vaccine-preventable HPV cancers.',
      '• Counsel on healthy nutrition, physical activity, screen time, and emotional well-being.',
      '• Update immunization card.',
    ].join('\n'),
  },
  {
    type: 'immunization',
    stage_code: 'IMM_11Y',
    stage_name: '10–12 Years — Tdap Booster',
    trigger_basis: 'child_age_days',
    trigger_value: 4015,
    order_index: 12,
    description: [
      'VACCINES TO ADMINISTER:',
      '• Tdap (Tetanus, reduced Diphtheria, acellular Pertussis — adolescent booster) — IM injection.',
      '• Annual Influenza Vaccine — IM injection (remind to repeat annually).',
      '',
      'CLINICAL TASKS:',
      '• Full adolescent health assessment before secondary school completion.',
      '• BMI, blood pressure, vision, and hearing screening.',
      '• Screen for scoliosis and postural issues.',
      '• Mental health screening: anxiety, academic stress, digital health.',
      '• Counsel on nutrition, regular exercise (60 min/day), sleep hygiene.',
      '• Update immunization card — marks adolescent immunization schedule complete.',
    ].join('\n'),
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SEEDER: upsert (safe — creates if missing, updates if changed)
// ─────────────────────────────────────────────────────────────────────────────
async function seed() {
  const { Op } = await import('sequelize');
  const allStages = [...pregnancyStages, ...immunizationStages];

  // Use upsert-style update for defined records
  for (const stage of allStages) {
    const existing = await StageTemplate.findOne({ where: { stage_code: stage.stage_code } });
    if (existing) {
      await existing.update({
        stage_name:    stage.stage_name,
        description:   stage.description,
        trigger_value: stage.trigger_value,
        order_index:   stage.order_index,
      });
    } else {
      await StageTemplate.create(stage);
    }
  }

  // Safely cleanup obsolete stage templates if they have no patient stages attached
  try {
    const validCodes = allStages.map(s => s.stage_code);
    const obsolete = await StageTemplate.findAll({
      where: { stage_code: { [Op.notIn]: validCodes } }
    });
    for (const obs of obsolete) {
      await obs.destroy().catch(() => {});
    }
  } catch (err) {
    // Ignore cleanup error if table or constraints prevent it
  }

  console.log(`✅ Stage templates: ${allStages.length} seeded/updated.`);
}

export { seed };

